In [56]:
import numpy as np
import pandas as pd

#### 1. Create a 6x3 integer array with values ranging from 10 to 100 such that the difference between each element is 5

In [57]:
array = np.arange(10,100,5,dtype=int).reshape(6,3)
array

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50],
       [55, 60, 65],
       [70, 75, 80],
       [85, 90, 95]])

#### 2. Create a numpy array using only starting point, length, and step

In [58]:
length, start, step = 15, 15, 5

In [59]:
array_2 = np.arange(start,start+length,step)
array_2

array([15, 20, 25])

#### 3. Find the index of 3rd repetition of number 2 in my_array

In [60]:
my_array = np.array([1, 2, 1, 1, 3, 4, 3, 1, 1, 2, 1, 1, 2])

In [61]:
indexes = np.where(my_array==2)
# indexes
indexes[0][2]  # or indexes[0][-1]

12

#### 4. Subtract the one_dim from the two_dim, such that each item of one_dim is subtracted from respective row of two_dim

In [62]:
two_dim = np.array([[30,30,30], [40,40,40], [50,50,50]])
one_dim = np.array([10,20,30])

In [63]:
two_dim - one_dim

array([[20, 10,  0],
       [30, 20, 10],
       [40, 30, 20]])

In [64]:
np.subtract(two_dim,one_dim)

array([[20, 10,  0],
       [30, 20, 10],
       [40, 30, 20]])

#### 5. Drop all nan values from my_array

In [65]:
my_array = np.array([1,2,3,np.nan,5,6,7,np.nan])

In [66]:
np.isnan(my_array)

array([False, False, False,  True, False, False, False,  True])

In [67]:
np.where(np.isnan(my_array)==True)

(array([3, 7], dtype=int64),)

In [68]:
my_array = np.delete(my_array,np.where(np.isnan(my_array)==True))

In [69]:
my_array

array([1., 2., 3., 5., 6., 7.])

#### 6. Find the mode of petal length (column No 3) in iris dataset

In [70]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
data = np.genfromtxt(url, delimiter=',', dtype='object')  

In [71]:
data

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.7', b'0.4', b'Iris-setosa'],
       [b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa'],
       [b'5.0', b'3.4', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.1', b'1.5', b'0.1', b'Iris-setosa'],
       [b'5.4', b'3.7', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.4', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.0', b'1.4', b'0.1', b'Iris-setosa'],
       [b'4.3', b'3.0', b'1.1', b'0.1', b'Iris-setosa'],
       [b'5.8', b'4.0', b'1.2', b'0.2', b'Iris-setosa'],
       [b'5.7', b'4.4', b'1.5', b'0.4', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.3', b'0.4', b'Iris-setosa'],
       [b'5.1', b'3.5', b'1.4',

In [72]:
data.shape

(150, 5)

In [73]:
data.ndim

2

In [74]:
data[:,2] # petalth column 

array([b'1.4', b'1.4', b'1.3', b'1.5', b'1.4', b'1.7', b'1.4', b'1.5',
       b'1.4', b'1.5', b'1.5', b'1.6', b'1.4', b'1.1', b'1.2', b'1.5',
       b'1.3', b'1.4', b'1.7', b'1.5', b'1.7', b'1.5', b'1.0', b'1.7',
       b'1.9', b'1.6', b'1.6', b'1.5', b'1.4', b'1.6', b'1.6', b'1.5',
       b'1.5', b'1.4', b'1.5', b'1.2', b'1.3', b'1.5', b'1.3', b'1.5',
       b'1.3', b'1.3', b'1.3', b'1.6', b'1.9', b'1.4', b'1.6', b'1.4',
       b'1.5', b'1.4', b'4.7', b'4.5', b'4.9', b'4.0', b'4.6', b'4.5',
       b'4.7', b'3.3', b'4.6', b'3.9', b'3.5', b'4.2', b'4.0', b'4.7',
       b'3.6', b'4.4', b'4.5', b'4.1', b'4.5', b'3.9', b'4.8', b'4.0',
       b'4.9', b'4.7', b'4.3', b'4.4', b'4.8', b'5.0', b'4.5', b'3.5',
       b'3.8', b'3.7', b'3.9', b'5.1', b'4.5', b'4.5', b'4.7', b'4.4',
       b'4.1', b'4.0', b'4.4', b'4.6', b'4.0', b'3.3', b'4.2', b'4.2',
       b'4.2', b'4.3', b'3.0', b'4.1', b'6.0', b'5.1', b'5.9', b'5.6',
       b'5.8', b'6.6', b'4.5', b'6.3', b'5.8', b'6.1', b'5.1', b'5.3',
      

In [75]:
import statistics as st
print(st.mode(data[:,2]))

b'1.5'


## reading this data from url is not good way for this dataset

In [101]:
data = pd.read_csv("C:/Users/ACER/Downloads/iris.data")
data    # I changed names of columns based on url that you sent(iris.names)

sepal length  sepal width  petal length  petal width            iris
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [102]:
mode = data['petal length'].mode()

In [103]:
mode

0    1.5
dtype: float64

#### 7. Normalize sepal length (column No 1) values so that they are exactly between 0 and 1

In [104]:
data['sepal length']=(data['sepal length']-data['sepal length'].mean())/data['sepal length'].std()

In [105]:
data

sepal length  sepal width  petal length  petal width            iris
0       -0.897674          3.5           1.4          0.2     Iris-setosa
1       -1.139200          3.0           1.4          0.2     Iris-setosa
2       -1.380727          3.2           1.3          0.2     Iris-setosa
3       -1.501490          3.1           1.5          0.2     Iris-setosa
4       -1.018437          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145      1.034539          3.0           5.2          2.3  Iris-virginica
146      0.551486          2.5           5.0          1.9  Iris-virginica
147      0.793012          3.0           5.2          2.0  Iris-virginica
148      0.430722          3.4           5.4          2.3  Iris-virginica
149      0.068433          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

#### 8. Get the positions of top 5 maximum values in my_array

In [76]:
np.random.seed(100)
my_array = np.random.uniform(1, 50, 20)

In [77]:
my_array

array([27.62684215, 14.64009987, 21.80136195, 42.39403048,  1.23122395,
        6.95688692, 33.86670515, 41.466785  ,  7.69862289, 29.17957314,
       44.67477576, 11.25090398, 10.08108276,  6.31046763, 11.76517714,
       48.95256545, 40.77247431,  9.42510962, 40.99501269, 14.42961361])

In [78]:
new_array = np.sort(my_array)
new_array_1=new_array[::-1]
new_array_1

array([48.95256545, 44.67477576, 42.39403048, 41.466785  , 40.99501269,
       40.77247431, 33.86670515, 29.17957314, 27.62684215, 21.80136195,
       14.64009987, 14.42961361, 11.76517714, 11.25090398, 10.08108276,
        9.42510962,  7.69862289,  6.95688692,  6.31046763,  1.23122395])

In [79]:
values = new_array_1[0:5]

In [80]:
sorter = np.argsort(my_array)
sorter[np.searchsorted(my_array, values, sorter=sorter)]

array([15, 10,  3,  7, 18], dtype=int64)

#### 9. Replace all values greater than 50 with 50 and less than 0 to 0 in my_array

In [81]:
np.random.seed(100)
my_array = np.random.uniform(-10,100, 30)

In [82]:
my_array[np.where(my_array>50)]=50
my_array[np.where(my_array<0)]=0
my_array

array([49.7745436 , 20.62063236, 36.69693498, 50.        ,  0.        ,
        3.37260329, 50.        , 50.        ,  5.03772487, 50.        ,
       50.        , 13.01223343, 10.38610415,  1.92145795, 14.16672419,
       50.        , 50.        ,  8.9135114 , 50.        , 20.14811217,
       37.4874602 , 50.        , 50.        , 26.97231451,  9.29514991,
       31.01152509,  0.        , 17.76689888, 50.        ,  0.        ])

#### 10. Read every 10th row and only specified columns of Boston Housing dataset as a dataframe, convert 'chas' column name to 'river', and write the output to an Excel file without index

In [83]:
url = "https://raw.githubusercontent.com/selva86/datasets/master/BostonHousing.csv"
columns = ['crim', 'chas', 'nox', 'tax', 'ptratio', 'medv']

In [84]:
dt1 = np.genfromtxt(url, delimiter=',', dtype='object')
[dt1[i] for i in range(11,dt1.shape[0],10)]

[array([b'0.22489', b'12.5', b'7.87', b'"0"', b'0.524', b'6.377', b'94.3',
        b'6.3467', b'5', b'311', b'15.2', b'392.52', b'20.45', b'15'],
       dtype=object),
 array([b'1.25179', b'0', b'8.14', b'"0"', b'0.538', b'5.57', b'98.1',
        b'3.7979', b'4', b'307', b'21', b'376.57', b'21.02', b'13.6'],
       dtype=object),
 array([b'1.13081', b'0', b'8.14', b'"0"', b'0.538', b'5.713', b'94.1',
        b'4.233', b'4', b'307', b'21', b'360.17', b'22.6', b'12.7'],
       dtype=object),
 array([b'0.03359', b'75', b'2.95', b'"0"', b'0.428', b'7.024', b'15.8',
        b'5.4011', b'3', b'252', b'18.3', b'395.62', b'1.98', b'34.9'],
       dtype=object),
 array([b'0.08873', b'21', b'5.64', b'"0"', b'0.439', b'5.963', b'45.7',
        b'6.8147', b'4', b'243', b'16.8', b'395.56', b'13.45', b'19.7'],
       dtype=object),
 array([b'0.14932', b'25', b'5.13', b'"0"', b'0.453', b'5.741', b'66.2',
        b'7.2254', b'8', b'284', b'19.7', b'395.11', b'13.15', b'18.7'],
       dtype=object),
 a

In [85]:
pd_dt = pd.read_csv(url,usecols=columns)
pd_dt

crim  chas    nox  tax  ptratio  medv
0    0.00632     0  0.538  296     15.3  24.0
1    0.02731     0  0.469  242     17.8  21.6
2    0.02729     0  0.469  242     17.8  34.7
3    0.03237     0  0.458  222     18.7  33.4
4    0.06905     0  0.458  222     18.7  36.2
..       ...   ...    ...  ...      ...   ...
501  0.06263     0  0.573  273     21.0  22.4
502  0.04527     0  0.573  273     21.0  20.6
503  0.06076     0  0.573  273     21.0  23.9
504  0.10959     0  0.573  273     21.0  22.0
505  0.04741     0  0.573  273     21.0  11.9

[506 rows x 6 columns]

In [86]:
pd_dt.columns = pd_dt.columns.str.replace('chas', 'river')

In [87]:
pd_dt.to_excel("Pandas_dataframe1.xlsx",index=None)

#### 11. Which decade was the most dangerous to live in the US according to crime rates data?

In [106]:
data = pd.read_csv("C:/Users/ACER/Downloads/US_Crime_Rates_1960_2014.csv")
data['Year'] = pd.to_datetime(data['Year'],format="%Y")
data.set_index('Year',inplace=True)
data = data.resample("10AS").sum() # get summation of each period crimes(decades)

In [107]:
data

Population      Total  Violent    Property  Murder  Forcible_Rape  \
Year                                                                            
1960-01-01  1915053175   49295900   4134930   45160900  106180         236720   
1970-01-01  2121193298  100991600   9607930   91383800  192230         554570   
1980-01-01  2371370069  131123369  14074328  117048900  206439         865639   
1990-01-01  2612825258  136582146  17527048  119053499  211664         998827   
2000-01-01  2947969117  115012044  13968056  100944369  163068         922499   
2010-01-01  1570146307   50167967   6072017   44095950   72867         421059   

            Robbery  Aggravated_assault  Burglary  Larceny_Theft  \
Year                                                               
1960-01-01  1633510             2158520  13321100       26547700   
1970-01-01  4159020             4702120  28486000       53157800   
1980-01-01  5383109             7619130  33073494       72040253   
1990-01-01  5748930            10568963  26750015       77679366   
2000-01-01  4230366             8652124  21565176       67970291   
2010-01-01  1749809             3764142  10125170       30401698   

            Vehicle_Theft  
Year                       
1960-01-01        5292100  
1970-01-01        9739900  
1980-01-01       11935411  
1990-01-01       14624418  
2000-01-01       11412834  
2010-01-01        3569080

In [108]:
maximum = data['Total'].max()
data.loc[data['Total']==maximum]

Population      Total  Violent    Property  Murder  Forcible_Rape  \
Year                                                                            
1990-01-01  2612825258  136582146  17527048  119053499  211664         998827   

            Robbery  Aggravated_assault  Burglary  Larceny_Theft  \
Year                                                               
1990-01-01  5748930            10568963  26750015       77679366   

            Vehicle_Theft  
Year                       
1990-01-01       14624418

#### 12. Drop the rows from the movies dataset where all elements are missing. Was there any?

In [88]:
dataset = pd.read_csv("C:/Users/ACER/Downloads/movies_metadata.csv")
dataset

adult                              belongs_to_collection    budget  \
0   False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000   
1   False                                                NaN  65000000   
2   False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0   
3   False                                                NaN  16000000   
4   False  {'id': 96871, 'name': 'Father of the Bride Col...         0   
5   False                                                NaN  60000000   
6   False                                                NaN  58000000   
7   False                                                NaN         0   
8   False                                                NaN  35000000   
9   False  {'id': 645, 'name': 'James Bond Collection', '...  58000000   
10  False                                                NaN  62000000   
11  False                                                NaN         0   
12  False  {'id': 117693, 'name': 'Balto Collection', 'po...         0   
13  False                                                NaN  44000000   
14  False                                                NaN  98000000   
15  False                                                NaN  52000000   
16  False                                                NaN  16500000   
17  False                                                NaN   4000000   
18  False  {'id': 3167, 'name': 'Ace Ventura Collection',...  30000000   
19  False                                                NaN  60000000   
20  False  {'id': 91698, 'name': 'Chili Palmer Collection...  30250000   
21  False                                                NaN         0   
22  False                                                NaN  50000000   
23  False                                                NaN         0   
24  False                                                NaN   3600000   
25  False                                                NaN         0   
26  False                                                NaN  12000000   
27  False                                                NaN         0   
28  False                                                NaN  18000000   
29  False                                                NaN         0   
30  False                                                NaN         0   
31  False                                                NaN  29500000   
32  False                                                NaN         0   
33  False  {'id': 9435, 'name': 'Babe Collection', 'poste...  30000000   
34  False                                                NaN         0   
35  False                                                NaN  11000000   
36  False                                                NaN         0   
37  False                                                NaN         0   
38  False                                                NaN  12000000   
39  False                                                NaN         0   
40  False                                                NaN         0   
41  False                                                NaN  10000000   
42  False                                                NaN  19000000   
43  False  {'id': 9818, 'name': 'Mortal Kombat Collection...  18000000   
44  False                                                NaN  20000000   
45  False                                                NaN  10000000   
46  False                                                NaN  33000000   
47  False  {'id': 136214, 'name': 'Pocahontas Collection'...  55000000   
48  False                                                NaN         0   
49  False                                                NaN   6000000   

                                               genres  \
0   [{'id': 16, 'name': 'Animation'}, {'id': 35, '...   
1   [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   
2   [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...   
3

In [89]:
dataset.shape 

(50, 24)

In [90]:
dataset1=dataset.dropna(how='all')

In [91]:
dataset1.shape # result: there is no all row that all elements are missing 

(50, 24)

#### 13. Merge df1 and df2 to get df3

In [92]:
df1 = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K2'],
                    'key2': ['K0', 'K1', 'K0', 'K1'],
                    'P': ['P0', 'P1', 'P2', 'P3'],
                    'Q': ['Q0', 'Q1', 'Q2', 'Q3']}) 
df2 = pd.DataFrame({'key1': ['K0', 'K1', 'K1', 'K2'],
                    'key2': ['K0', 'K0', 'K0', 'K0'],
                    'R': ['R0', 'R1', 'R2', 'R3'],
                    'S': ['S0', 'S1', 'S2', 'S3']})
df3 = pd.DataFrame({'key1': ['K0', 'K0', 'K1', 'K1', 'K2', 'K2'],
                    'key2': ['K0', 'K1', 'K0', 'K0', 'K1', 'K0'],
                    'P': ['P0', 'P1', 'P2', 'P2', 'P3', np.nan],
                    'Q': ['Q0', 'Q1', 'Q2', 'Q2', 'Q3', np.nan],
                    'R': ['R0', np.nan, 'R1', 'R2', np.nan, 'R3'],
                    'S': ['S0', np.nan, 'S1', 'S2', np.nan, 'S3']})
print("Original DataFrames:\nDataframe 1:\n", df1, '\nDataFrame 2:\n', df2)
print("Desired DataFrame:\n", df3)

Original DataFrames:
Dataframe 1:
   key1 key2   P   Q
0   K0   K0  P0  Q0
1   K0   K1  P1  Q1
2   K1   K0  P2  Q2
3   K2   K1  P3  Q3 
DataFrame 2:
   key1 key2   R   S
0   K0   K0  R0  S0
1   K1   K0  R1  S1
2   K1   K0  R2  S2
3   K2   K0  R3  S3
Desired DataFrame:
   key1 key2    P    Q    R    S
0   K0   K0   P0   Q0   R0   S0
1   K0   K1   P1   Q1  NaN  NaN
2   K1   K0   P2   Q2   R1   S1
3   K1   K0   P2   Q2   R2   S2
4   K2   K1   P3   Q3  NaN  NaN
5   K2   K0  NaN  NaN   R3   S3


In [93]:
df = df1.merge(df2,how='outer')
df

key1 key2    P    Q    R    S
0   K0   K0   P0   Q0   R0   S0
1   K0   K1   P1   Q1  NaN  NaN
2   K1   K0   P2   Q2   R1   S1
3   K1   K0   P2   Q2   R2   S2
4   K2   K1   P3   Q3  NaN  NaN
5   K2   K0  NaN  NaN   R3   S3

#### 14. Merge left_df and right_df to get df

In [94]:
left_df = pd.DataFrame({'transaction_id': ['A', 'B', 'C', 'D'], 
                       'user_id': ['Peter', 'John', 'John', 'Anna'],
                       'value': [43, 76, 54, 88]})
right_df = pd.DataFrame({'user_id_r': ['Paul', 'Mary', 'John', 'Anna', 'Edward'],
                        'favorite_color': ['blue', 'blue', 'red', np.nan, 'orange']})
df = pd.DataFrame({'transaction_id': ['A', 'B', 'C', 'D'],
                   'user_id': ['Peter', 'John', 'John', 'Anna'],
                   'value': [43, 76, 54, 88],
                   'favorite_color': ['blue', 'blue', 'red', np.nan]})
print("Original DataFrames:\nDataframe 1:\n", left_df, '\nDataFrame 2:\n', right_df)
print("Desired DataFrame:\n", df)

Original DataFrames:
Dataframe 1:
   transaction_id user_id  value
0              A   Peter     43
1              B    John     76
2              C    John     54
3              D    Anna     88 
DataFrame 2:
   user_id_r favorite_color
0      Paul           blue
1      Mary           blue
2      John            red
3      Anna            NaN
4    Edward         orange
Desired DataFrame:
   transaction_id user_id  value favorite_color
0              A   Peter     43           blue
1              B    John     76           blue
2              C    John     54            red
3              D    Anna     88            NaN


In [95]:
df = left_df.join(right_df,lsuffix="_left")

In [96]:
df.drop("user_id_r",inplace=True, axis=1)
df

transaction_id user_id  value favorite_color
0              A   Peter     43           blue
1              B    John     76           blue
2              C    John     54            red
3              D    Anna     88            NaN

#### 15.  Convert year and day of year into a single date column to get the desired DataFrame 

In [97]:
data1 = pd.DataFrame({"year": [2005, 2008, 2010, 2022],
                      "day_of_the_year": [250, 364, 1, 176]})
data2 = pd.DataFrame({"year": [2005, 2008, 2010, 2022],
                      "day_of_the_year": [250, 364, 1, 176],
                      "date": ['2005-09-07', '2008-12-29', '2010-01-01', '2022-06-25']})
print("Original DataFrame:\n", data1)
print("Desired DataFrame:\n", data2)

Original DataFrame:
    year  day_of_the_year
0  2005              250
1  2008              364
2  2010                1
3  2022              176
Desired DataFrame:
    year  day_of_the_year        date
0  2005              250  2005-09-07
1  2008              364  2008-12-29
2  2010                1  2010-01-01
3  2022              176  2022-06-25


In [98]:
data1_df = pd.DataFrame(data1)
data1_df

year  day_of_the_year
0  2005              250
1  2008              364
2  2010                1
3  2022              176

In [99]:
data1_df['new_column'] = data1_df['year'].astype(str) + data1_df['day_of_the_year'].astype(str)
data1_df

year  day_of_the_year new_column
0  2005              250    2005250
1  2008              364    2008364
2  2010                1      20101
3  2022              176    2022176

In [100]:
data1_df["date"] = pd.to_datetime(data1_df["new_column"], format = "%Y%j")
data1_df = data1_df.drop("new_column", axis=1)
data1_df

year  day_of_the_year       date
0  2005              250 2005-09-07
1  2008              364 2008-12-29
2  2010                1 2010-01-01
3  2022              176 2022-06-25